import Link from "next/link"
import { Scale } from "lucide-react"
import { Button } from "@/components/ui/button"

const links=[["About","/about"],["Arbitrators","/arbitrators"],["Model Clause","/model-clause"],["Resources","/resources"],["Facilities","/facilities"]]

export function PublicShell({children}:{children:React.ReactNode}){return <main className="dark min-h-screen bg-background text-foreground"><header className="border-b border-border bg-background"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6"><Link href="/" className="flex items-center gap-3 font-serif font-bold"><span className="flex size-10 items-center justify-center border border-primary text-primary"><Scale className="size-5"/></span><span className="hidden sm:block">Arbitration &amp; Dispute Resolution Centre</span></Link><nav className="hidden items-center gap-5 text-sm lg:flex" aria-label="Public navigation">{links.map(([label,href])=><Link key={href} href={href} className="text-muted-foreground hover:text-primary">{label}</Link>)}</nav><div className="flex gap-2"><Button variant="outline" render={<Link href="/login"/>}>Portal Login</Button><Button className="hidden sm:inline-flex" render={<Link href="/refer-dispute"/>}>Refer a Dispute</Button></div></div></header>{children}<footer className="border-t border-border bg-card"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:px-6"><p>© 2026 Arbitration &amp; Dispute Resolution Centre</p><p>Hyderabad, Telangana, India</p></div></footer></main>}

export function PublicHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="border-b border-border bg-card"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 md:py-24"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-semibold text-balance md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-pretty text-muted-foreground">{description}</p></div></section>}
