import Link from "next/link"
import { CalendarDays, FileText, Gavel } from "lucide-react"
import { isDemoUserId } from "@/auth"
import { prisma } from "@/lib/prisma"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <Card><CardHeader className="flex-row items-center justify-between"><CardDescription>{label}</CardDescription>{icon}</CardHeader><CardContent><p className="font-serif text-3xl font-semibold">{value}</p></CardContent></Card>}

const demoCases = [
  { id: "demo-case-1", title: "Aster Infra v. Meridian Works", caseNumber: "ARB/2026/0047", status: "TRIBUNAL_CONSTITUTED", bookings: [{ id: "demo-hearing-1" }], documents: [{ id: "demo-document-1" }, { id: "demo-document-2" }, { id: "demo-document-3" }] },
  { id: "demo-case-2", title: "Nova Energy v. Crestline Power", caseNumber: "ARB/2026/0042", status: "PLEADINGS", bookings: [{ id: "demo-hearing-2" }], documents: [{ id: "demo-document-4" }, { id: "demo-document-5" }] },
  { id: "demo-case-3", title: "Parkview Hotels v. Aranya Group", caseNumber: "ARB/2026/0038", status: "AWAITING_DEPOSIT", bookings: [], documents: [{ id: "demo-document-6" }] },
]

export async function CaseWorkspace({ user, basePath }: { user: { id: string; role: string; name?: string | null }, basePath: string }) {
  const demoMode = isDemoUserId(user.id)
  const cases = demoMode ? demoCases : await prisma.case.findMany({ where: user.role === "PARTY" ? { partyId: user.id } : { arbitrators: { some: { arbitrator: { userId: user.id } } } }, include: { bookings: { where: { status: "CONFIRMED" } }, documents: { select: { id: true } } }, orderBy: { updatedAt: "desc" } })

  return <div className="min-h-full bg-muted/30"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-4 py-8 md:px-8 md:py-10"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><p className="text-sm text-muted-foreground">Welcome, {user.name}</p>{demoMode && <Badge variant="secondary">Demo mode</Badge>}</div><h1 className="font-serif text-4xl font-semibold">{user.role === "PARTY" ? "Your matters" : "Assigned matters"}</h1></div>{user.role === "PARTY" && (demoMode ? <Button disabled><Gavel data-icon="inline-start" />Filing disabled in demo</Button> : <Button render={<Link href="/portal/cases/new" />}><Gavel data-icon="inline-start" />File new case</Button>)}</header>{demoMode && <Card className="border-primary/20 bg-secondary"><CardContent><p className="text-sm leading-relaxed"><strong>Preview workspace:</strong> These sample matters are read-only. Documents, filings, hearings, and updates are not connected to a database.</p></CardContent></Card>}<section className="grid gap-4 sm:grid-cols-3"><Metric label="Active matters" value={cases.filter(item => item.status !== "CLOSED").length} icon={<Gavel className="size-5" />} /><Metric label="Confirmed hearings" value={cases.reduce((sum,item)=>sum+item.bookings.length,0)} icon={<CalendarDays className="size-5" />} /><Metric label="Documents" value={cases.reduce((sum,item)=>sum+item.documents.length,0)} icon={<FileText className="size-5" />} /></section><Card><CardHeader><CardTitle className="font-serif">Case docket</CardTitle><CardDescription>{demoMode ? "Representative matters for previewing this role workspace." : "Open a matter to view its tribunal, timeline, documents, fees, and hearings."}</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{cases.length ? cases.map(item=>demoMode ? <div key={item.id} className="flex flex-col justify-between gap-3 rounded-lg border p-4 sm:flex-row sm:items-center"><div><p className="font-medium">{item.title}</p><p className="font-mono text-xs text-muted-foreground">{item.caseNumber}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{item.status.replaceAll("_"," ")}</Badge><Badge variant="secondary">Read only</Badge></div></div> : <Link key={item.id} href={`${basePath}/cases/${item.id}`} className="flex flex-col justify-between gap-3 rounded-lg border p-4 transition-colors hover:bg-muted sm:flex-row sm:items-center"><div><p className="font-medium">{item.title}</p><p className="font-mono text-xs text-muted-foreground">{item.caseNumber}</p></div><Badge variant="outline">{item.status.replaceAll("_"," ")}</Badge></Link>) : <p className="py-12 text-center text-muted-foreground">No matters are currently assigned to this account.</p>}</CardContent></Card></div></div>
}
