import { z } from "zod"

export const fileSchema = z.object({ fileName: z.string().min(1), mimeType: z.string().min(1), contentBase64: z.string().min(1) })
export const empanelmentSchema = z.object({ applicantName: z.string().min(2), applicantEmail: z.string().email(), applicantPhone: z.string().min(7), professionalBackground: z.string().min(40), proposedSpecializations: z.array(z.enum(["COMMERCIAL", "BANKING", "FINANCIAL", "INFRASTRUCTURE", "LOAN_RECOVERY", "OTHER"])).min(1), documents: z.array(fileSchema).min(1) })
export const referralSchema = z.object({ referrerName: z.string().min(2), referrerEmail: z.string().email(), referrerPhone: z.string().optional(), entityType: z.enum(["BANK", "NBFC", "LAW_FIRM", "ADVOCATE", "INDIVIDUAL", "OTHER"]), disputeSummary: z.string().min(40) })
export const bookingSchema = z.object({ facilityId: z.string().min(1), caseId: z.string().optional(), bookingType: z.enum(["PHYSICAL_ROOM", "VIRTUAL_HEARING", "HYBRID"]), startTime: z.coerce.date(), endTime: z.coerce.date(), requesterName: z.string().min(2), requesterEmail: z.string().email(), requesterPhone: z.string().optional(), secretarialAssistanceRequired: z.boolean().default(false) }).refine((v) => v.endTime > v.startTime, { message: "End time must follow start time" })
export const caseSchema = z.object({ title: z.string().min(5), description: z.string().min(20), counterpartyName: z.string().min(2), referringEntityType: z.enum(["BANK", "NBFC", "LAW_FIRM", "ADVOCATE", "INDIVIDUAL", "OTHER"]), claimAmount: z.coerce.number().positive(), isFastTrack: z.boolean().default(false), isEmergency: z.boolean().default(false) })
export const documentSchema = fileSchema.extend({ documentType: z.enum(["FILING", "EVIDENCE", "ORDER", "AWARD"]) })
export const tribunalSchema = z.object({ appointments: z.array(z.object({ arbitratorId: z.string(), role: z.enum(["SOLE", "PRESIDING", "CLAIMANT_NOMINEE", "RESPONDENT_NOMINEE", "EMERGENCY_ARBITRATOR"]) })).min(1) }).superRefine(({ appointments }, ctx) => { const roles = appointments.map((a) => a.role).sort(); const valid = roles.join(",") === "EMERGENCY_ARBITRATOR" || roles.join(",") === "SOLE" || roles.join(",") === ["CLAIMANT_NOMINEE", "PRESIDING", "RESPONDENT_NOMINEE"].sort().join(","); if (!valid) ctx.addIssue({ code: "custom", message: "Select one sole arbitrator, one emergency arbitrator, or an exact three-member tribunal" }) })
