import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { requireRole } from "@/lib/authorization"
import { prisma } from "@/lib/prisma"

export default async function Page() {
  await requireRole("ADMIN")
  const applications = await prisma.empanelmentApplication.findMany({ include: { _count: { select: { documents: true } } }, orderBy: { createdAt: "desc" } })
  return <main className="mx-auto flex max-w-7xl flex-col gap-6 p-4 md:p-8"><header><p className="text-sm text-muted-foreground">Panel governance</p><h1 className="font-serif text-4xl font-semibold">Empanelment</h1><p className="mt-2 text-muted-foreground">Track document review, interviews, decisions, and registration fees.</p></header><Card><CardHeader><CardTitle>Application queue</CardTitle><CardDescription>{applications.filter((item) => !["APPROVED", "REJECTED"].includes(item.stage)).length} applications require action</CardDescription></CardHeader><CardContent className="overflow-x-auto px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Applicant</TableHead><TableHead>Specializations</TableHead><TableHead>Documents</TableHead><TableHead>Interview</TableHead><TableHead>Fee</TableHead><TableHead>Stage</TableHead></TableRow></TableHeader><TableBody>{applications.map((item) => <TableRow key={item.id}><TableCell className="pl-6"><p className="font-medium">{item.applicantName}</p><p className="text-xs text-muted-foreground">{item.applicantEmail}</p></TableCell><TableCell>{Array.isArray(item.proposedSpecializations) ? (item.proposedSpecializations as string[]).join(", ").replaceAll("_", " ") : "—"}</TableCell><TableCell>{item._count.documents}</TableCell><TableCell>{item.interviewScheduledAt?.toLocaleString("en-IN") ?? "Not scheduled"}</TableCell><TableCell><Badge variant={item.registrationFeePaid ? "secondary" : "outline"}>{item.registrationFeePaid ? "Paid" : "Unpaid"}</Badge></TableCell><TableCell><Badge variant="outline">{item.stage.replaceAll("_", " ")}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></main>
}
